import { writeFile } from 'node:fs/promises';
import { examples } from '../src/catalog.mjs';
import { prepare, runCase } from '../src/runner.mjs';

const experiments = {
  '01': 'Keep the granted scope identical but change the request from a staging investigation to an employee audit. Then remove a required scope and confirm that preflight stops before inference.',
  '02': 'Change “for this weekend only” to “from now on.” Add two contradictory updates without dates. Decide what evidence should be required before replacing either memory.',
  '03': 'Change “all supported platforms” to the exact platform named in the artifact. Add an artifact that is internally contradictory and inspect which claim IDs are flagged.',
  '04': 'Change only the time period, language, policy version, or tenant. Tenant and expiry changes should be settled by code before a request exists.',
  '05': 'Return a complete report for the wrong date, then a partial report for the right date. Distinguish a semantic mismatch from the deterministic truncated flag.',
  '06': 'Change a failed read into a write with an unknown outcome. Confirm that the recovery path becomes reconciliation without consulting the model.',
  '07': 'Shrink the character budget below the mandatory constraint. Then replace an irrelevant snippet with genuinely new evidence and inspect the selected IDs, not just the action name.',
  '08': 'Paraphrase the prohibition without losing it. Then move “not verified” to “verified” and inspect the missing obligation IDs.',
  '09': 'Keep the titles identical while changing the traces. Then make titles different but keep the precise causal signature. Neither result should close an issue.',
  '10': 'Add another equivalent question wording to the comparison group. Run repeated live reports with a pinned model and check both action agreement and the underlying distributions.',
};

for (const example of examples) {
  const number = example.id.slice(0, 2);
  const sample = example.cases.find(c => prepare(example, c).request);
  const { request } = prepare(example, sample);
  const result = await runCase(example, sample);
  const cases = example.cases.map(c => `| \`${c.id}\` | ${c.note} | \`${c.expected}\` |`).join('\n');
  const questionList = Object.entries(request.questions).map(([id, q]) => `### \`${id}\` · ${q.type}\n\n${q.instructions}\n${q.criteria ? '\n```json\n' + JSON.stringify(q.criteria, null, 2) + '\n```\n' : ''}`).join('\n');
  const text = `# ${number} · ${example.title}

${example.hook}

**Pattern:** ${example.pattern}.

## Why this decision matters

${example.why}

## Run it

From the repository root:

\`\`\`sh
npm start -- run ${number}
npm start -- request ${number} --case ${sample.id}
npm start -- run ${number} --case ${sample.id} --live
\`\`\`

The first command uses authored response fixtures. The last needs a TypeSafe API key and makes a real request. No command performs the proposed downstream action.

## Read the evidence

Example input: **${sample.id}**.

\`\`\`json
${JSON.stringify(sample.state, null, 2)}
\`\`\`

## Ask focused questions

${questionList}

All these questions see the same state independently. None sees another question's answer. Review [example.mjs](example.mjs) for the policy and [cases.mjs](cases.mjs) for the full case set.

## Follow the policy

The authored fixture produces this application result:

\`\`\`json
${JSON.stringify(result.outcome, null, 2)}
\`\`\`

The \`reason\` is written by application code, not generated by Jev. Fixture numbers illustrate policy branches; they are not measurements or predictions of model behavior.

## Try the contrasting cases

| Case | What changes | Intended policy outcome |
| :-- | :-- | :-- |
${cases}

These intended outcomes are author judgments. A live disagreement is evidence to inspect, not a result to quietly relabel.

## Change one thing

${experiments[number]}

Edit the case state, inspect the request, then run with \`--live\` to see what Jev does. Editing only the state in fixture mode does **not** change its scripted response. Change fixture values separately when testing a policy branch.

## Where it stops

${example.boundary}

**Known failure mode:** ${example.failure}

The included baseline is intentionally limited. Its purpose is to expose a particular shortcut, not to represent the strongest alternative. See [evaluation notes](../../docs/evaluation.md).

[Back to all ten examples](../../README.md#pick-a-problem) · [API notes](../../docs/api-contract.md)
`;
  await writeFile(new URL('README.md', example.source), text);
}
console.log(`Updated ${examples.length} example guides.`);
